<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="nuglaf" failures="0" tests="7" name="TestNG.TestNG.TestNGFeatures" time="0.017" errors="1" timestamp="25 Jan 2021 03:32:43 GMT" skipped="6">
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="RealPage" time="0.000">
    <skipped/>
  </testcase> <!-- RealPage -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="loginTest" time="0.004">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="HomePage" time="0.000">
    <skipped/>
  </testcase> <!-- HomePage -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="loginTest" time="0.003">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="loginTest" time="0.003">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at TestNG.TestNG.TestNGFeatures.loginTest(TestNGFeatures.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="loginTest" time="0.007">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="TestNG.TestNG.TestNGFeatures" name="SearchPage" time="0.000">
    <skipped/>
  </testcase> <!-- SearchPage -->
</testsuite> <!-- TestNG.TestNG.TestNGFeatures -->
